### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by trabelsi29** [googlesamples/android-AccelerometerPlay#2]
Hi
Please can u explain me this function : 

public void computePhysics(float sx, float sy, float dT) {

                final float ax = -sx/5;
                final float ay = -sy/5;

                mPosX += mVelX * dT + ax * dT * dT / 2;
                mPosY += mVelY * dT + ay * dT * dT / 2;

                mVelX += ax * dT;
                mVelY += ay * dT;
            }

And what's the :  mVelX /  mVelY and sx, sy and dT
Thanks !

**Comment by MatrixMike** [comment]
The mVelX / mVelY would appear to be velocity (m could be max or min) and dT is part of calculus to estimate the acceleration and thus slow down or speed up the movement of the balls.

**Comment by keremkambur** [comment]
Hi,

The formula to calculate distance and velocity is clear but why did we multiply with negative and divided by 5 the given acceleration vectors ? Is this for the UI purposes ? Or a constant as filter ?

Thanks.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
